# Generated by Django 4.0.6 on 2024-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0002_banda_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='image',
        ),
        migrations.AddField(
            model_name='festival',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='festivais/images'),
        ),
    ]
