# Generated by Django 4.0.6 on 2024-04-20 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.IntegerField()),
                ('access_conditions', models.TextField()),
                ('career_opportunities', models.TextField()),
                ('competences', models.TextField()),
                ('direction_contact', models.CharField(max_length=200)),
                ('direction_email', models.EmailField(max_length=254)),
                ('course_ects', models.IntegerField()),
                ('course_name', models.CharField(max_length=200)),
                ('course_secretariat_contact', models.CharField(max_length=200)),
                ('course_secretariat_email', models.EmailField(max_length=254)),
                ('future_studies', models.TextField()),
                ('infrastructure', models.TextField()),
                ('objectives', models.TextField()),
                ('presentation', models.TextField()),
                ('scientific_area', models.CharField(max_length=200)),
                ('semesters', models.IntegerField()),
                ('recipients', models.TextField()),
                ('guest_teachers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programming_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scientific_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.TextField()),
                ('program', models.TextField()),
                ('objectives', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=2)),
                ('ects', models.IntegerField()),
                ('curricularIUnitReadableCode', models.CharField(max_length=20)),
                ('scientific_area', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.scientific_area')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='curso/images')),
                ('resume', models.TextField()),
                ('subject', models.ManyToManyField(to='curso.subject')),
            ],
        ),
        migrations.AddField(
            model_name='scientific_area',
            name='teachers',
            field=models.ManyToManyField(to='curso.teacher'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='curso/images')),
                ('video', models.URLField(default='')),
                ('concepts', models.TextField()),
                ('technologies', models.TextField()),
                ('repository', models.URLField(default='')),
                ('programming_languages', models.ManyToManyField(to='curso.programming_language')),
            ],
        ),
        migrations.CreateModel(
            name='Flat_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('subjects', models.ManyToManyField(to='curso.subject')),
            ],
        ),
    ]
