# Generated by Django 4.0.6 on 2024-04-20 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
    ]
