# Generated by Django 4.0.6 on 2024-04-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_remove_scientific_area_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientific_area',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
