# Generated by Django 4.0.6 on 2024-04-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_scientific_area_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
