# Generated by Django 4.0.6 on 2024-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumLink',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='Black_question_mark.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(default='Black_question_mark.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(default='Black_question_mark.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='music',
            name='musicLink',
            field=models.URLField(default=''),
        ),
    ]
