# Generated by Django 4.0.6 on 2024-03-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_alter_album_artist_alter_music_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bands.music'),
            preserve_default=False,
        ),
    ]
