# Generated by Django 4.0.6 on 2024-03-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_album_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='musics',
            field=models.ManyToManyField(to='bands.music'),
        ),
    ]
