# Generated by Django 4.0.6 on 2024-04-19 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_remove_album_album_album_musics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='band',
            name='albums',
            field=models.ManyToManyField(to='bands.album'),
        ),
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=180)),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bands/images'),
        ),
        migrations.AlterField(
            model_name='album',
            name='releaseDate',
            field=models.DateField(default=datetime.timedelta(seconds=180)),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bands/images'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bands/images'),
        ),
    ]
