# Generated by Django 4.0.6 on 2024-04-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_remove_album_artist_remove_music_artist_band_albums_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
