# Generated by Django 4.0.6 on 2024-04-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_alter_album_releasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_tracks', to='bands.album'),
        ),
        migrations.AddField(
            model_name='musician',
            name='band',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
        ),
        migrations.AlterField(
            model_name='album',
            name='musics',
            field=models.ManyToManyField(related_name='albums_included', to='bands.music'),
        ),
        migrations.AlterField(
            model_name='band',
            name='albums',
            field=models.ManyToManyField(related_name='associated_bands_albums', to='bands.album'),
        ),
        migrations.AlterField(
            model_name='band',
            name='artists',
            field=models.ManyToManyField(related_name='associated_bands', to='bands.musician'),
        ),
    ]
