# Generated by Django 4.0.6 on 2024-05-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
    ]
