# Generated by Django 4.0.6 on 2024-05-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0005_rename_user_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='User',
        ),
    ]
