# Generated by Django 4.0.6 on 2024-05-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0006_rename_userinfo_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
    atomic = False