# Generated by Django 4.0.6 on 2024-05-26 22:57

import artigos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artigos', '0008_userprofile_user'),
    ]

    operations = [

    ]
