# Generated by Django 4.0.6 on 2024-05-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0009_alter_userprofile_user'),
    ]

    operations = [

    ]
