# Generated by Django 4.0.6 on 2024-05-27 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0010_remove_userprofile_user'),
    ]

    operations = [
    ]
