# Generated by Django 4.0.6 on 2024-05-27 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0011_auto_20240527_0216'),
    ]

    operations = [
    ]
